### ISSUE TITLE
wrong directory in configure fail2ban section

### ISSUE THREAD

**Issue by Faustino-CIMA** [gacallea/itn1_cluster#1]
cp /root/itn1_cluster_repo/itn1_cluster/files/jail.local /etc/fail2ban/jail.local 
cp: cannot stat '/root/itn1_cluster_repo/itn1_cluster/files/jail.local': No such file or directory

it should be 

cp /root/itn1_cluster_repo/files/jail.local /etc/fail2ban/jail.local

**Comment by gacallea** [comment]
thanks for catching this one @Faustino-CIMA :) it is now fixed.

**Comment by Faustino-CIMA** [comment]
Youre welcome Andrea, thanks for the awsome guide and the quick fix.

**Comment by gacallea** [comment]
Let me know how it goes with the setup, and tweet if you can :)
